### ISSUE TITLE
Add 'companions' column to SOURCES table

### ISSUE THREAD

**Issue by hover2pi** [BDNYC/BDNYCdb#12]
Recently added a 'components' column to SOURCES to link individual sources to their unresolved combined source. Add a 'companions' column to SOURCES so that components can be linked to each other.

**Comment by hover2pi** [comment]
Sources now have 'companions' column to link objects in the same system and 'components' column to link an unresolved system to its resolved components.

**Comment by emilurice** [comment]
Nice! (Not sure where this email goes...)
