### ISSUE TITLE
python version requirement?

### ISSUE THREAD

**Issue by kelle** [BDNYC/BDNYCdb#17]
In the tutorial, it specfically says to make an environment with Python 2.7. Is there something which is not compatible with Python 3.6? If so, should Python 2.7 be put in the requirements.txt?

**Comment by ECGonzales** [comment]
Yes all of the code for the database is written in Python 2. I believe that the requirements.txt is just for the packages.

**Comment by dr-rodriguez** [comment]
AstrodbWeb only runs on Python 2.7, hence the requirement for the tutorial. 
If you just want to use the database, both Python 2 and 3 are fine. Astrodbkit is tested for 2.7 and 3.5; we should add 3.6.
